var PRELOAD = {
  "images": [
    "img/penguin-real.png",
    "img/penguin-silly.png",
    "img/fish-real.png",
    "img/fish-silly.png",
    "img/fish-blank-resize.png",
    "img/fish-placeholder.png",
    "img/level0.png",
    "img/level1.png",
    "img/level2.png",
    "img/level3.png",
    "img/level4.png",
    "img/level5.png"
  ],
  "sounds": [
    "snd/w_dripping_B_3.wav",
    "snd/w_jiggle_B.wav",
    "snd/w_envy_B.wav",
    "snd/w_soaking_B_3.wav",
    "snd/w_shoving_B_3.wav",
    "snd/w_corner_B_2.wav",
    "snd/w_snore_B.wav",
    "snd/nw_bodemenk_B_2.wav",
    "snd/nw_fishint_B.wav",
    "snd/w_river_B_2.wav",
    "snd/w_losing_B_2.wav",
    "snd/nw_bulgint_B.wav",
    "snd/nw_bannimp_B.wav",
    "snd/nw_demenk_B.wav",
    "snd/nw_lomenk_B.wav",
    "snd/nw_amemf_B.wav",
    "snd/nw_fomemf_B.wav",
    "snd/w_crawlin_B_2.wav",
    "snd/w_chewin_B.wav",
    "snd/w_pocket_B.wav",
    "snd/w_file_B.wav",
    "snd/w_hugging_B_3.wav",
    "snd/w_pasting_B_2.wav",
    "snd/w_soccer_B.wav",
    "snd/w_movement_B.wav",
    "snd/nw_breathint_B.wav",
    "snd/nw_sendink_B.wav",
    "snd/w_counting_B.wav",
    "snd/w_moment_B.wav",
    "snd/nw_sarmenz_B.wav",
    "snd/nw_cademp_B.wav",
    "snd/nw_argemp_B.wav",
    "snd/nw_quib_B.wav",
    "snd/nw_swip_B.wav",
    "snd/nw_darp_B.wav",
    "snd/w_leapin_B.wav",
    "snd/w_burnin_B_2.wav",
    "snd/w_puppet_B_2.wav",
    "snd/w_giggle_B.wav",
    "snd/w_mixing_B_3.wav",
    "snd/w_climbing_B_2.wav",
    "snd/w_swimmer_B.wav",
    "snd/w_treatment_B_2.wav",
    "snd/w_skate_B.wav",
    "snd/nw_kissint_B.wav",
    "snd/w_comment_B.wav",
    "snd/w_chatting_B.wav",
    "snd/nw_sedge_B.wav",
    "snd/nw_tust_B.wav",
    "snd/nw_colb_B.wav",
    "snd/nw_pouk_B_2.wav",
    "snd/nw_mouk_B_2.wav",
    "snd/nw_tabe_B.wav",
    "snd/w_stopping_B_3.wav",
    "snd/w_teachin_B.wav",
    "snd/w_towel_B.wav",
    "snd/w_pity_B.wav",
    "snd/w_faking_B.wav",
    "snd/w_dreaming_B.wav",
    "snd/w_milk_B.wav",
    "snd/w_winner_B.wav",
    "snd/w_basement_B.wav",
    "snd/nw_bankert_B.wav",
    "snd/nw_foolint_B.wav",
    "snd/w_brother_B.wav",
    "snd/nw_tral_B.wav",
    "snd/nw_niyn_B.wav",
    "snd/nw_gowg_B_4.wav",
    "snd/nw_skihjh_B.wav",
    "snd/nw_plehl_B_2.wav",
    "snd/nw_slihg_B_2.wav",
    "snd/w_bully_B.wav",
    "snd/w_cooking_B_3.wav",
    "snd/w_brushing_B_3.wav",
    "snd/w_knocking_B_3.wav",
    "snd/nw_touchint_B.wav",
    "snd/w_clicking_B_3.wav",
    "snd/nw_waske_B.wav",
    "snd/nw_vowp_B_3.wav",
    "snd/nw_broon_B.wav",
    "snd/nw_resk_B.wav",
    "snd/w_dripping_B_3.wav",
    "snd/w_thinking_B_3.wav",
    "snd/w_dropping_B.wav",
    "snd/w_soaking_B_3.wav",
    "snd/w_shoving_B_3.wav",
    "snd/w_corn_B_2.wav",
    "snd/w_blue_B.wav",
    "snd/w_road_B.wav",
    "snd/w_fish_B_2.wav",
    "snd/nw_riv_B.wav",
    "snd/nw_loov_B.wav",
    "snd/nw_pottelt_B_3.wav",
    "snd/nw_timbelt_B.wav",
    "snd/nw_prowent_B_2.wav",
    "snd/nw_summinch_B.wav",
    "snd/nw_flewis_B.wav",
    "snd/nw_deepelt_B.wav",
    "snd/w_crawling_B_3.wav",
    "snd/w_chewing_B_3.wav",
    "snd/w_speaking_B_3.wav",
    "snd/w_paying_B.wav",
    "snd/w_hugging_B_3.wav",
    "snd/w_pasting_B_2.wav",
    "snd/w_sock_B.wav",
    "snd/w_move_B.wav",
    "snd/w_breathe_B.wav",
    "snd/w_send_B.wav",
    "snd/nw_coump_B_4.wav",
    "snd/nw_mo_B.wav",
    "snd/nw_dragolt_B.wav",
    "snd/nw_bettulk_B.wav",
    "snd/nw_bruschel_B.wav",
    "snd/nw_vapif_B_2.wav",
    "snd/nw_bridgom_B.wav",
    "snd/nw_gheetim_B.wav",
    "snd/w_leaping_B_3.wav",
    "snd/w_burning_B.wav",
    "snd/w_sweeping_B_2.wav",
    "snd/w_blinking_B.wav",
    "snd/w_mixing_B_3.wav",
    "snd/w_climbing_B_2.wav",
    "snd/w_swim_B.wav",
    "snd/w_treat_B_2.wav",
    "snd/w_fly_B.wav",
    "snd/w_miss_B_2.wav",
    "snd/nw_com_B.wav",
    "snd/nw_chaz_B.wav",
    "snd/nw_solix_B.wav",
    "snd/nw_spirenk_B_2.wav",
    "snd/nw_hundram_B.wav",
    "snd/nw_plighka_B_2.wav",
    "snd/nw_scuppen_B_2.wav",
    "snd/nw_jummel_B.wav",
    "snd/w_stopping_B_3.wav",
    "snd/w_teaching_B_2.wav",
    "snd/w_growing_B_3.wav",
    "snd/w_spinning_B.wav",
    "snd/w_faking_B.wav",
    "snd/w_dreaming_B.wav",
    "snd/w_push_B_2.wav",
    "snd/w_win_B.wav",
    "snd/w_base_B.wav",
    "snd/w_thank_B.wav",
    "snd/w_pool_B.wav",
    "snd/nw_broth_B.wav",
    "snd/nw_smertha_B.wav",
    "snd/nw_luhd_B.wav",
    "snd/nw_nihldz_B_2.wav",
    "snd/nw_tehjh_B_3.wav",
    "snd/nw_kaek_B.wav",
    "snd/nw_trahm_B.wav",
    "snd/w_itching_B_2.wav",
    "snd/w_ruining_B.wav",
    "snd/w_riddle_B.wav",
    "snd/w_bragging_B_2.wav",
    "snd/w_spraying_B.wav",
    "snd/nw_buzzerp_B.wav",
    "snd/nw_thwoxit_B.wav",
    "snd/nw_snowast_B.wav",
    "snd/nw_ploufip_B.wav",
    "snd/nw_crayint_B.wav"
  ]
}

 var LIST1 = [
  {
    "block": "a",
    "item_number": "c1",
    "prime": "bending",
    "prime_sound": "snd/w_bending_B_3.wav",
    "target": "stealing",
    "target_sound": "snd/w_stealing_B_2.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "c29",
    "prime": "filming",
    "prime_sound": "snd/w_filming_B.wav",
    "target": "dripping",
    "target_sound": "snd/w_dripping_B_3.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "c58",
    "prime": "workin",
    "prime_sound": "snd/w_workin_B.wav",
    "target": "thinking",
    "target_sound": "snd/w_thinking_B_3.wav",
    "type": "critical",
    "c_f_type": "in_",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "c45",
    "prime": "drummin",
    "prime_sound": "snd/w_drummin_B.wav",
    "target": "dropping",
    "target_sound": "snd/w_dropping_B.wav",
    "type": "critical",
    "c_f_type": "in",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "c10",
    "prime": "tackle",
    "prime_sound": "snd/w_tackle_B.wav",
    "target": "soaking",
    "target_sound": "snd/w_soaking_B_3.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "c15",
    "prime": "trumpet",
    "prime_sound": "snd/w_trumpet_B_2.wav",
    "target": "shoving",
    "target_sound": "snd/w_shoving_B_3.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "f1",
    "prime": "corner",
    "prime_sound": "snd/w_corner_B_2.wav",
    "target": "corn",
    "target_sound": "snd/w_corn_B_2.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "f40",
    "prime": "snore",
    "prime_sound": "snd/w_snore_B.wav",
    "target": "blue",
    "target_sound": "snd/w_blue_B.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "f82",
    "prime": "bodemenk",
    "prime_sound": "snd/nw_bodemenk_B_2.wav",
    "target": "road",
    "target_sound": "snd/w_road_B.wav",
    "type": "filler",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "f67",
    "prime": "fishint",
    "prime_sound": "snd/nw_fishint_B.wav",
    "target": "fish",
    "target_sound": "snd/w_fish_B_2.wav",
    "type": "filler",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "f46",
    "prime": "river",
    "prime_sound": "snd/w_river_B_2.wav",
    "target": "riv",
    "target_sound": "snd/nw_riv_B.wav",
    "type": "filler",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "a",
    "item_number": "f64",
    "prime": "losing",
    "prime_sound": "snd/w_losing_B_2.wav",
    "target": "loov",
    "target_sound": "snd/nw_loov_B.wav",
    "type": "filler",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "a",
    "item_number": "f108",
    "prime": "bulgint",
    "prime_sound": "snd/nw_bulgint_B.wav",
    "target": "pottelt",
    "target_sound": "snd/nw_pottelt_B_3.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "a",
    "item_number": "f110",
    "prime": "bannimp",
    "prime_sound": "snd/nw_bannimp_B.wav",
    "target": "timbelt",
    "target_sound": "snd/nw_timbelt_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "a",
    "item_number": "f112",
    "prime": "demenk",
    "prime_sound": "snd/nw_demenk_B.wav",
    "target": "prowent",
    "target_sound": "snd/nw_prowent_B_2.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "a",
    "item_number": "F113",
    "prime": "lomenk",
    "prime_sound": "snd/nw_lomenk_B.wav",
    "target": "summinch",
    "target_sound": "snd/nw_summinch_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "a",
    "item_number": "F114",
    "prime": "amemf",
    "prime_sound": "snd/nw_amemf_B.wav",
    "target": "flewis",
    "target_sound": "snd/nw_flewis_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "a",
    "item_number": "F115",
    "prime": "fomemf",
    "prime_sound": "snd/nw_fomemf_B.wav",
    "target": "deepelt",
    "target_sound": "snd/nw_deepelt_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "c2",
    "prime": "holding",
    "prime_sound": "snd/w_holding_B.wav",
    "target": "crawling",
    "target_sound": "snd/w_crawling_B_3.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "c33",
    "prime": "mowing",
    "prime_sound": "snd/w_mowing_B_2.wav",
    "target": "chewing",
    "target_sound": "snd/w_chewing_B_3.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "c26",
    "prime": "hikin",
    "prime_sound": "snd/w_hikin_B.wav",
    "target": "speaking",
    "target_sound": "snd/w_speaking_B_3.wav",
    "type": "critical",
    "c_f_type": "in_",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "c27",
    "prime": "cryin",
    "prime_sound": "snd/w_cryin_B_4.wav",
    "target": "paying",
    "target_sound": "snd/w_paying_B.wav",
    "type": "critical",
    "c_f_type": "in",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "c9",
    "prime": "pickle",
    "prime_sound": "snd/w_pickle_B.wav",
    "target": "hugging",
    "target_sound": "snd/w_hugging_B_3.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "c30",
    "prime": "trouble",
    "prime_sound": "snd/w_trouble_B.wav",
    "target": "pasting",
    "target_sound": "snd/w_pasting_B_2.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "f4",
    "prime": "soccer",
    "prime_sound": "snd/w_soccer_B.wav",
    "target": "sock",
    "target_sound": "snd/w_sock_B.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "f27",
    "prime": "movement",
    "prime_sound": "snd/w_movement_B.wav",
    "target": "move",
    "target_sound": "snd/w_move_B.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "f66",
    "prime": "breathint",
    "prime_sound": "snd/nw_breathint_B.wav",
    "target": "breathe",
    "target_sound": "snd/w_breathe_B.wav",
    "type": "filler",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "f68",
    "prime": "sendink",
    "prime_sound": "snd/nw_sendink_B.wav",
    "target": "send",
    "target_sound": "snd/w_send_B.wav",
    "type": "filler",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "f63",
    "prime": "counting",
    "prime_sound": "snd/w_counting_B.wav",
    "target": "coump",
    "target_sound": "snd/nw_coump_B_4.wav",
    "type": "filler",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "f27",
    "prime": "moment",
    "prime_sound": "snd/w_moment_B.wav",
    "target": "mo",
    "target_sound": "snd/nw_mo_B.wav",
    "type": "filler",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "F116",
    "prime": "sarmenz",
    "prime_sound": "snd/nw_sarmenz_B.wav",
    "target": "dragolt",
    "target_sound": "snd/nw_dragolt_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "F123",
    "prime": "cademp",
    "prime_sound": "snd/nw_cademp_B.wav",
    "target": "bettulk",
    "target_sound": "snd/nw_bettulk_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "F128",
    "prime": "argemp",
    "prime_sound": "snd/nw_argemp_B.wav",
    "target": "bruschel",
    "target_sound": "snd/nw_bruschel_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "F133",
    "prime": "quib",
    "prime_sound": "snd/nw_quib_B.wav",
    "target": "vapif",
    "target_sound": "snd/nw_vapif_B_2.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "F136",
    "prime": "swip",
    "prime_sound": "snd/nw_swip_B.wav",
    "target": "bridgom",
    "target_sound": "snd/nw_bridgom_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "F139",
    "prime": "darp",
    "prime_sound": "snd/nw_darp_B.wav",
    "target": "gheetim",
    "target_sound": "snd/nw_gheetim_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "c14",
    "prime": "burping",
    "prime_sound": "snd/w_burping_B.wav",
    "target": "leaping",
    "target_sound": "snd/w_leaping_B_3.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "c49",
    "prime": "wasting",
    "prime_sound": "snd/w_wasting_B.wav",
    "target": "burning",
    "target_sound": "snd/w_burning_B.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "c32",
    "prime": "flamin",
    "prime_sound": "snd/w_flamin_B.wav",
    "target": "sweeping",
    "target_sound": "snd/w_sweeping_B_2.wav",
    "type": "critical",
    "c_f_type": "in_",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "c39",
    "prime": "peckin",
    "prime_sound": "snd/w_peckin_B.wav",
    "target": "blinking",
    "target_sound": "snd/w_blinking_B.wav",
    "type": "critical",
    "c_f_type": "in",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "c51",
    "prime": "carry",
    "prime_sound": "snd/w_carry_B_2.wav",
    "target": "mixing",
    "target_sound": "snd/w_mixing_B_3.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "c44",
    "prime": "shimmy",
    "prime_sound": "snd/w_shimmy_B.wav",
    "target": "climbing",
    "target_sound": "snd/w_climbing_B_2.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "f9",
    "prime": "swimmer",
    "prime_sound": "snd/w_swimmer_B.wav",
    "target": "swim",
    "target_sound": "snd/w_swim_B.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "f32",
    "prime": "treatment",
    "prime_sound": "snd/w_treatment_B_2.wav",
    "target": "treat",
    "target_sound": "snd/w_treat_B_2.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "f34",
    "prime": "skate",
    "prime_sound": "snd/w_skate_B.wav",
    "target": "fly",
    "target_sound": "snd/w_fly_B.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "f70",
    "prime": "kissint",
    "prime_sound": "snd/nw_kissint_B.wav",
    "target": "miss",
    "target_sound": "snd/w_miss_B_2.wav",
    "type": "filler",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "f49",
    "prime": "comment",
    "prime_sound": "snd/w_comment_B.wav",
    "target": "com",
    "target_sound": "snd/nw_com_B.wav",
    "type": "filler",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "f57",
    "prime": "chatting",
    "prime_sound": "snd/w_chatting_B.wav",
    "target": "chaz",
    "target_sound": "snd/nw_chaz_B.wav",
    "type": "filler",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "F142",
    "prime": "sedge",
    "prime_sound": "snd/nw_sedge_B.wav",
    "target": "solix",
    "target_sound": "snd/nw_solix_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "F145",
    "prime": "tust",
    "prime_sound": "snd/nw_tust_B.wav",
    "target": "spirenk",
    "target_sound": "snd/nw_spirenk_B_2.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "F147",
    "prime": "colb",
    "prime_sound": "snd/nw_colb_B.wav",
    "target": "hundram",
    "target_sound": "snd/nw_hundram_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "F149",
    "prime": "pouk",
    "prime_sound": "snd/nw_pouk_B_2.wav",
    "target": "plighka",
    "target_sound": "snd/nw_plighka_B_2.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "F151",
    "prime": "mouk",
    "prime_sound": "snd/nw_mouk_B_2.wav",
    "target": "scuppen",
    "target_sound": "snd/nw_scuppen_B_2.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "F156",
    "prime": "tabe",
    "prime_sound": "snd/nw_tabe_B.wav",
    "target": "jummel",
    "target_sound": "snd/nw_jummel_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "d",
    "item_number": "c16",
    "prime": "saving",
    "prime_sound": "snd/w_saving_B.wav",
    "target": "stopping",
    "target_sound": "snd/w_stopping_B_3.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "c54",
    "prime": "washing",
    "prime_sound": "snd/w_washing_B.wav",
    "target": "teaching",
    "target_sound": "snd/w_teaching_B_2.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "c48",
    "prime": "plowin",
    "prime_sound": "snd/w_plowin_B_2.wav",
    "target": "growing",
    "target_sound": "snd/w_growing_B_3.wav",
    "type": "critical",
    "c_f_type": "in_",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "c37",
    "prime": "messin",
    "prime_sound": "snd/w_messin_B.wav",
    "target": "spinning",
    "target_sound": "snd/w_spinning_B.wav",
    "type": "critical",
    "c_f_type": "in",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "c56",
    "prime": "wiggle",
    "prime_sound": "snd/w_wiggle_B.wav",
    "target": "faking",
    "target_sound": "snd/w_faking_B.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "c13",
    "prime": "limit",
    "prime_sound": "snd/w_limit_B.wav",
    "target": "dreaming",
    "target_sound": "snd/w_dreaming_B.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "f36",
    "prime": "milk",
    "prime_sound": "snd/w_milk_B.wav",
    "target": "push",
    "target_sound": "snd/w_push_B_2.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "f14",
    "prime": "winner",
    "prime_sound": "snd/w_winner_B.wav",
    "target": "win",
    "target_sound": "snd/w_win_B.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "f22",
    "prime": "basement",
    "prime_sound": "snd/w_basement_B.wav",
    "target": "base",
    "target_sound": "snd/w_base_B.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "f77",
    "prime": "bankert",
    "prime_sound": "snd/nw_bankert_B.wav",
    "target": "thank",
    "target_sound": "snd/w_thank_B.wav",
    "type": "filler",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "f88",
    "prime": "foolint",
    "prime_sound": "snd/nw_foolint_B.wav",
    "target": "pool",
    "target_sound": "snd/w_pool_B.wav",
    "type": "filler",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "f48",
    "prime": "brother",
    "prime_sound": "snd/w_brother_B.wav",
    "target": "broth",
    "target_sound": "snd/nw_broth_B.wav",
    "type": "filler",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "d",
    "item_number": "F164",
    "prime": "tral",
    "prime_sound": "snd/nw_tral_B.wav",
    "target": "smertha",
    "target_sound": "snd/nw_smertha_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "d",
    "item_number": "F168",
    "prime": "niyn",
    "prime_sound": "snd/nw_niyn_B.wav",
    "target": "luhd",
    "target_sound": "snd/nw_luhd_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "d",
    "item_number": "F169",
    "prime": "gowg",
    "prime_sound": "snd/nw_gowg_B_4.wav",
    "target": "nihldz",
    "target_sound": "snd/nw_nihldz_B_2.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "d",
    "item_number": "F173",
    "prime": "skihjh",
    "prime_sound": "snd/nw_skihjh_B.wav",
    "target": "tehjh",
    "target_sound": "snd/nw_tehjh_B_3.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "d",
    "item_number": "F179",
    "prime": "plehl",
    "prime_sound": "snd/nw_plehl_B_2.wav",
    "target": "kaek",
    "target_sound": "snd/nw_kaek_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "d",
    "item_number": "F195",
    "prime": "slihg",
    "prime_sound": "snd/nw_slihg_B_2.wav",
    "target": "trahm",
    "target_sound": "snd/nw_trahm_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "practice",
    "item_number": "p1",
    "prime": "bully",
    "prime_sound": "snd/w_bully_B.wav",
    "target": "itching",
    "target_sound": "snd/w_itching_B_2.wav",
    "type": "practice",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "practice",
    "item_number": "p2",
    "prime": "cooking",
    "prime_sound": "snd/w_cooking_B_3.wav",
    "target": "ruining",
    "target_sound": "snd/w_ruining_B.wav",
    "type": "practice",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "practice",
    "item_number": "p3",
    "prime": "brushing",
    "prime_sound": "snd/w_brushing_B_3.wav",
    "target": "riddle",
    "target_sound": "snd/w_riddle_B.wav",
    "type": "practice",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "practice",
    "item_number": "p4",
    "prime": "knocking",
    "prime_sound": "snd/w_knocking_B_3.wav",
    "target": "bragging",
    "target_sound": "snd/w_bragging_B_2.wav",
    "type": "practice",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "practice",
    "item_number": "p5",
    "prime": "touchint",
    "prime_sound": "snd/nw_touchint_B.wav",
    "target": "spraying",
    "target_sound": "snd/w_spraying_B.wav",
    "type": "practice",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "practice",
    "item_number": "p6",
    "prime": "clicking",
    "prime_sound": "snd/w_clicking_B_3.wav",
    "target": "buzzerp",
    "target_sound": "snd/nw_buzzerp_B.wav",
    "type": "practice",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "practice",
    "item_number": "p7",
    "prime": "waske",
    "prime_sound": "snd/nw_waske_B.wav",
    "target": "thwoxit",
    "target_sound": "snd/nw_thwoxit_B.wav",
    "type": "practice",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "practice",
    "item_number": "p8",
    "prime": "vowp",
    "prime_sound": "snd/nw_vowp_B_3.wav",
    "target": "snowast",
    "target_sound": "snd/nw_snowast_B.wav",
    "type": "practice",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "practice",
    "item_number": "p9",
    "prime": "broon",
    "prime_sound": "snd/nw_broon_B.wav",
    "target": "ploufip",
    "target_sound": "snd/nw_ploufip_B.wav",
    "type": "practice",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "practice",
    "item_number": "p10",
    "prime": "resk",
    "prime_sound": "snd/nw_resk_B.wav",
    "target": "crayint",
    "target_sound": "snd/nw_crayint_B.wav",
    "type": "practice",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  }
]
var LIST2 = [
  {
    "block": "a",
    "item_number": "c1",
    "prime": "bendin",
    "prime_sound": "snd/w_bendin_B.wav",
    "target": "stealing",
    "target_sound": "snd/w_stealing_B_2.wav",
    "type": "critical",
    "c_f_type": "in",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "c29",
    "prime": "filmin",
    "prime_sound": "snd/w_filmin_B_2.wav",
    "target": "dripping",
    "target_sound": "snd/w_dripping_B_3.wav",
    "type": "critical",
    "c_f_type": "in",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "c58",
    "prime": "jiggle",
    "prime_sound": "snd/w_jiggle_B.wav",
    "target": "thinking",
    "target_sound": "snd/w_thinking_B_3.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "c45",
    "prime": "envy",
    "prime_sound": "snd/w_envy_B.wav",
    "target": "dropping",
    "target_sound": "snd/w_dropping_B.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "c10",
    "prime": "risking",
    "prime_sound": "snd/w_risking_B.wav",
    "target": "soaking",
    "target_sound": "snd/w_soaking_B_3.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "c15",
    "prime": "bluffing",
    "prime_sound": "snd/w_bluffing_B_2.wav",
    "target": "shoving",
    "target_sound": "snd/w_shoving_B_3.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "f1",
    "prime": "corner",
    "prime_sound": "snd/w_corner_B_2.wav",
    "target": "corn",
    "target_sound": "snd/w_corn_B_2.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "f40",
    "prime": "snore",
    "prime_sound": "snd/w_snore_B.wav",
    "target": "blue",
    "target_sound": "snd/w_blue_B.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "f82",
    "prime": "bodemenk",
    "prime_sound": "snd/nw_bodemenk_B_2.wav",
    "target": "road",
    "target_sound": "snd/w_road_B.wav",
    "type": "filler",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "f67",
    "prime": "fishint",
    "prime_sound": "snd/nw_fishint_B.wav",
    "target": "fish",
    "target_sound": "snd/w_fish_B_2.wav",
    "type": "filler",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "f46",
    "prime": "river",
    "prime_sound": "snd/w_river_B_2.wav",
    "target": "riv",
    "target_sound": "snd/nw_riv_B.wav",
    "type": "filler",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "a",
    "item_number": "f64",
    "prime": "losing",
    "prime_sound": "snd/w_losing_B_2.wav",
    "target": "loov",
    "target_sound": "snd/nw_loov_B.wav",
    "type": "filler",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "a",
    "item_number": "f108",
    "prime": "bulgint",
    "prime_sound": "snd/nw_bulgint_B.wav",
    "target": "pottelt",
    "target_sound": "snd/nw_pottelt_B_3.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "a",
    "item_number": "f110",
    "prime": "bannimp",
    "prime_sound": "snd/nw_bannimp_B.wav",
    "target": "timbelt",
    "target_sound": "snd/nw_timbelt_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "a",
    "item_number": "f112",
    "prime": "demenk",
    "prime_sound": "snd/nw_demenk_B.wav",
    "target": "prowent",
    "target_sound": "snd/nw_prowent_B_2.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "a",
    "item_number": "F113",
    "prime": "lomenk",
    "prime_sound": "snd/nw_lomenk_B.wav",
    "target": "summinch",
    "target_sound": "snd/nw_summinch_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "a",
    "item_number": "F114",
    "prime": "amemf",
    "prime_sound": "snd/nw_amemf_B.wav",
    "target": "flewis",
    "target_sound": "snd/nw_flewis_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "a",
    "item_number": "F115",
    "prime": "fomemf",
    "prime_sound": "snd/nw_fomemf_B.wav",
    "target": "deepelt",
    "target_sound": "snd/nw_deepelt_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "c2",
    "prime": "holdin",
    "prime_sound": "snd/w_holdin_B.wav",
    "target": "crawling",
    "target_sound": "snd/w_crawling_B_3.wav",
    "type": "critical",
    "c_f_type": "in",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "c33",
    "prime": "mowin",
    "prime_sound": "snd/w_mowin_B.wav",
    "target": "chewing",
    "target_sound": "snd/w_chewing_B_3.wav",
    "type": "critical",
    "c_f_type": "in",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "c26",
    "prime": "pocket",
    "prime_sound": "snd/w_pocket_B.wav",
    "target": "speaking",
    "target_sound": "snd/w_speaking_B_3.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "c27",
    "prime": "file",
    "prime_sound": "snd/w_file_B.wav",
    "target": "paying",
    "target_sound": "snd/w_paying_B.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "c9",
    "prime": "clanging",
    "prime_sound": "snd/w_clanging_B_2.wav",
    "target": "hugging",
    "target_sound": "snd/w_hugging_B_3.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "c30",
    "prime": "hoping",
    "prime_sound": "snd/w_hoping_B.wav",
    "target": "pasting",
    "target_sound": "snd/w_pasting_B_2.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "f4",
    "prime": "soccer",
    "prime_sound": "snd/w_soccer_B.wav",
    "target": "sock",
    "target_sound": "snd/w_sock_B.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "f27",
    "prime": "movement",
    "prime_sound": "snd/w_movement_B.wav",
    "target": "move",
    "target_sound": "snd/w_move_B.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "f66",
    "prime": "breathint",
    "prime_sound": "snd/nw_breathint_B.wav",
    "target": "breathe",
    "target_sound": "snd/w_breathe_B.wav",
    "type": "filler",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "f68",
    "prime": "sendink",
    "prime_sound": "snd/nw_sendink_B.wav",
    "target": "send",
    "target_sound": "snd/w_send_B.wav",
    "type": "filler",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "f63",
    "prime": "counting",
    "prime_sound": "snd/w_counting_B.wav",
    "target": "coump",
    "target_sound": "snd/nw_coump_B_4.wav",
    "type": "filler",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "f27",
    "prime": "moment",
    "prime_sound": "snd/w_moment_B.wav",
    "target": "mo",
    "target_sound": "snd/nw_mo_B.wav",
    "type": "filler",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "F116",
    "prime": "sarmenz",
    "prime_sound": "snd/nw_sarmenz_B.wav",
    "target": "dragolt",
    "target_sound": "snd/nw_dragolt_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "F123",
    "prime": "cademp",
    "prime_sound": "snd/nw_cademp_B.wav",
    "target": "bettulk",
    "target_sound": "snd/nw_bettulk_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "F128",
    "prime": "argemp",
    "prime_sound": "snd/nw_argemp_B.wav",
    "target": "bruschel",
    "target_sound": "snd/nw_bruschel_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "F133",
    "prime": "quib",
    "prime_sound": "snd/nw_quib_B.wav",
    "target": "vapif",
    "target_sound": "snd/nw_vapif_B_2.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "F136",
    "prime": "swip",
    "prime_sound": "snd/nw_swip_B.wav",
    "target": "bridgom",
    "target_sound": "snd/nw_bridgom_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "F139",
    "prime": "darp",
    "prime_sound": "snd/nw_darp_B.wav",
    "target": "gheetim",
    "target_sound": "snd/nw_gheetim_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "c14",
    "prime": "burpin",
    "prime_sound": "snd/w_burpin_B.wav",
    "target": "leaping",
    "target_sound": "snd/w_leaping_B_3.wav",
    "type": "critical",
    "c_f_type": "in",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "c49",
    "prime": "wastin",
    "prime_sound": "snd/w_wastin_B.wav",
    "target": "burning",
    "target_sound": "snd/w_burning_B.wav",
    "type": "critical",
    "c_f_type": "in",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "c32",
    "prime": "puppet",
    "prime_sound": "snd/w_puppet_B_2.wav",
    "target": "sweeping",
    "target_sound": "snd/w_sweeping_B_2.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "c39",
    "prime": "giggle",
    "prime_sound": "snd/w_giggle_B.wav",
    "target": "blinking",
    "target_sound": "snd/w_blinking_B.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "c51",
    "prime": "waxing",
    "prime_sound": "snd/w_waxing_B.wav",
    "target": "mixing",
    "target_sound": "snd/w_mixing_B_3.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "c44",
    "prime": "blooming",
    "prime_sound": "snd/w_blooming_B.wav",
    "target": "climbing",
    "target_sound": "snd/w_climbing_B_2.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "f9",
    "prime": "swimmer",
    "prime_sound": "snd/w_swimmer_B.wav",
    "target": "swim",
    "target_sound": "snd/w_swim_B.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "f32",
    "prime": "treatment",
    "prime_sound": "snd/w_treatment_B_2.wav",
    "target": "treat",
    "target_sound": "snd/w_treat_B_2.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "f34",
    "prime": "skate",
    "prime_sound": "snd/w_skate_B.wav",
    "target": "fly",
    "target_sound": "snd/w_fly_B.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "f70",
    "prime": "kissint",
    "prime_sound": "snd/nw_kissint_B.wav",
    "target": "miss",
    "target_sound": "snd/w_miss_B_2.wav",
    "type": "filler",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "f49",
    "prime": "comment",
    "prime_sound": "snd/w_comment_B.wav",
    "target": "com",
    "target_sound": "snd/nw_com_B.wav",
    "type": "filler",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "f57",
    "prime": "chatting",
    "prime_sound": "snd/w_chatting_B.wav",
    "target": "chaz",
    "target_sound": "snd/nw_chaz_B.wav",
    "type": "filler",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "F142",
    "prime": "sedge",
    "prime_sound": "snd/nw_sedge_B.wav",
    "target": "solix",
    "target_sound": "snd/nw_solix_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "F145",
    "prime": "tust",
    "prime_sound": "snd/nw_tust_B.wav",
    "target": "spirenk",
    "target_sound": "snd/nw_spirenk_B_2.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "F147",
    "prime": "colb",
    "prime_sound": "snd/nw_colb_B.wav",
    "target": "hundram",
    "target_sound": "snd/nw_hundram_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "F149",
    "prime": "pouk",
    "prime_sound": "snd/nw_pouk_B_2.wav",
    "target": "plighka",
    "target_sound": "snd/nw_plighka_B_2.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "F151",
    "prime": "mouk",
    "prime_sound": "snd/nw_mouk_B_2.wav",
    "target": "scuppen",
    "target_sound": "snd/nw_scuppen_B_2.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "F156",
    "prime": "tabe",
    "prime_sound": "snd/nw_tabe_B.wav",
    "target": "jummel",
    "target_sound": "snd/nw_jummel_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "d",
    "item_number": "c16",
    "prime": "savin",
    "prime_sound": "snd/w_savin_B.wav",
    "target": "stopping",
    "target_sound": "snd/w_stopping_B_3.wav",
    "type": "critical",
    "c_f_type": "in",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "c54",
    "prime": "washin",
    "prime_sound": "snd/w_washin_B.wav",
    "target": "teaching",
    "target_sound": "snd/w_teaching_B_2.wav",
    "type": "critical",
    "c_f_type": "in",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "c48",
    "prime": "towel",
    "prime_sound": "snd/w_towel_B.wav",
    "target": "growing",
    "target_sound": "snd/w_growing_B_3.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "c37",
    "prime": "pity",
    "prime_sound": "snd/w_pity_B.wav",
    "target": "spinning",
    "target_sound": "snd/w_spinning_B.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "c56",
    "prime": "lacking",
    "prime_sound": "snd/w_lacking_B.wav",
    "target": "faking",
    "target_sound": "snd/w_faking_B.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "c13",
    "prime": "carving",
    "prime_sound": "snd/w_carving_B.wav",
    "target": "dreaming",
    "target_sound": "snd/w_dreaming_B.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "f36",
    "prime": "milk",
    "prime_sound": "snd/w_milk_B.wav",
    "target": "push",
    "target_sound": "snd/w_push_B_2.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "f14",
    "prime": "winner",
    "prime_sound": "snd/w_winner_B.wav",
    "target": "win",
    "target_sound": "snd/w_win_B.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "f22",
    "prime": "basement",
    "prime_sound": "snd/w_basement_B.wav",
    "target": "base",
    "target_sound": "snd/w_base_B.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "f77",
    "prime": "bankert",
    "prime_sound": "snd/nw_bankert_B.wav",
    "target": "thank",
    "target_sound": "snd/w_thank_B.wav",
    "type": "filler",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "f88",
    "prime": "foolint",
    "prime_sound": "snd/nw_foolint_B.wav",
    "target": "pool",
    "target_sound": "snd/w_pool_B.wav",
    "type": "filler",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "f48",
    "prime": "brother",
    "prime_sound": "snd/w_brother_B.wav",
    "target": "broth",
    "target_sound": "snd/nw_broth_B.wav",
    "type": "filler",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "d",
    "item_number": "F164",
    "prime": "tral",
    "prime_sound": "snd/nw_tral_B.wav",
    "target": "smertha",
    "target_sound": "snd/nw_smertha_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "d",
    "item_number": "F168",
    "prime": "niyn",
    "prime_sound": "snd/nw_niyn_B.wav",
    "target": "luhd",
    "target_sound": "snd/nw_luhd_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "d",
    "item_number": "F169",
    "prime": "gowg",
    "prime_sound": "snd/nw_gowg_B_4.wav",
    "target": "nihldz",
    "target_sound": "snd/nw_nihldz_B_2.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "d",
    "item_number": "F173",
    "prime": "skihjh",
    "prime_sound": "snd/nw_skihjh_B.wav",
    "target": "tehjh",
    "target_sound": "snd/nw_tehjh_B_3.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "d",
    "item_number": "F179",
    "prime": "plehl",
    "prime_sound": "snd/nw_plehl_B_2.wav",
    "target": "kaek",
    "target_sound": "snd/nw_kaek_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "d",
    "item_number": "F195",
    "prime": "slihg",
    "prime_sound": "snd/nw_slihg_B_2.wav",
    "target": "trahm",
    "target_sound": "snd/nw_trahm_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "practice",
    "item_number": "p1",
    "prime": "bully",
    "prime_sound": "snd/w_bully_B.wav",
    "target": "itching",
    "target_sound": "snd/w_itching_B_2.wav",
    "type": "practice",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "practice",
    "item_number": "p2",
    "prime": "cooking",
    "prime_sound": "snd/w_cooking_B_3.wav",
    "target": "ruining",
    "target_sound": "snd/w_ruining_B.wav",
    "type": "practice",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "practice",
    "item_number": "p3",
    "prime": "brushing",
    "prime_sound": "snd/w_brushing_B_3.wav",
    "target": "riddle",
    "target_sound": "snd/w_riddle_B.wav",
    "type": "practice",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "practice",
    "item_number": "p4",
    "prime": "knocking",
    "prime_sound": "snd/w_knocking_B_3.wav",
    "target": "bragging",
    "target_sound": "snd/w_bragging_B_2.wav",
    "type": "practice",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "practice",
    "item_number": "p5",
    "prime": "touchint",
    "prime_sound": "snd/nw_touchint_B.wav",
    "target": "spraying",
    "target_sound": "snd/w_spraying_B.wav",
    "type": "practice",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "practice",
    "item_number": "p6",
    "prime": "clicking",
    "prime_sound": "snd/w_clicking_B_3.wav",
    "target": "buzzerp",
    "target_sound": "snd/nw_buzzerp_B.wav",
    "type": "practice",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "practice",
    "item_number": "p7",
    "prime": "waske",
    "prime_sound": "snd/nw_waske_B.wav",
    "target": "thwoxit",
    "target_sound": "snd/nw_thwoxit_B.wav",
    "type": "practice",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "practice",
    "item_number": "p8",
    "prime": "vowp",
    "prime_sound": "snd/nw_vowp_B_3.wav",
    "target": "snowast",
    "target_sound": "snd/nw_snowast_B.wav",
    "type": "practice",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "practice",
    "item_number": "p9",
    "prime": "broon",
    "prime_sound": "snd/nw_broon_B.wav",
    "target": "ploufip",
    "target_sound": "snd/nw_ploufip_B.wav",
    "type": "practice",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "practice",
    "item_number": "p10",
    "prime": "resk",
    "prime_sound": "snd/nw_resk_B.wav",
    "target": "crayint",
    "target_sound": "snd/nw_crayint_B.wav",
    "type": "practice",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  }
]

var LIST3 = [
  {
    "block": "a",
    "item_number": "c1",
    "prime": "wrestle",
    "prime_sound": "snd/w_wrestle_B.wav",
    "target": "stealing",
    "target_sound": "snd/w_stealing_B_2.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "c29",
    "prime": "copy",
    "prime_sound": "snd/w_copy_B.wav",
    "target": "dripping",
    "target_sound": "snd/w_dripping_B_3.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "c58",
    "prime": "working",
    "prime_sound": "snd/w_working_B.wav",
    "target": "thinking",
    "target_sound": "snd/w_thinking_B_3.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "c45",
    "prime": "drumming",
    "prime_sound": "snd/w_drumming_B.wav",
    "target": "dropping",
    "target_sound": "snd/w_dropping_B.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "c10",
    "prime": "riskin",
    "prime_sound": "snd/w_riskin_B.wav",
    "target": "soaking",
    "target_sound": "snd/w_soaking_B_3.wav",
    "type": "critical",
    "c_f_type": "in",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "c15",
    "prime": "bluffin",
    "prime_sound": "snd/w_bluffin_B.wav",
    "target": "shoving",
    "target_sound": "snd/w_shoving_B_3.wav",
    "type": "critical",
    "c_f_type": "in",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "f1",
    "prime": "corner",
    "prime_sound": "snd/w_corner_B_2.wav",
    "target": "corn",
    "target_sound": "snd/w_corn_B_2.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "f40",
    "prime": "snore",
    "prime_sound": "snd/w_snore_B.wav",
    "target": "blue",
    "target_sound": "snd/w_blue_B.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "f82",
    "prime": "bodemenk",
    "prime_sound": "snd/nw_bodemenk_B_2.wav",
    "target": "road",
    "target_sound": "snd/w_road_B.wav",
    "type": "filler",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "f67",
    "prime": "fishint",
    "prime_sound": "snd/nw_fishint_B.wav",
    "target": "fish",
    "target_sound": "snd/w_fish_B_2.wav",
    "type": "filler",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "a",
    "item_number": "f46",
    "prime": "river",
    "prime_sound": "snd/w_river_B_2.wav",
    "target": "riv",
    "target_sound": "snd/nw_riv_B.wav",
    "type": "filler",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "a",
    "item_number": "f64",
    "prime": "losing",
    "prime_sound": "snd/w_losing_B_2.wav",
    "target": "loov",
    "target_sound": "snd/nw_loov_B.wav",
    "type": "filler",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "a",
    "item_number": "f108",
    "prime": "bulgint",
    "prime_sound": "snd/nw_bulgint_B.wav",
    "target": "pottelt",
    "target_sound": "snd/nw_pottelt_B_3.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "a",
    "item_number": "f110",
    "prime": "bannimp",
    "prime_sound": "snd/nw_bannimp_B.wav",
    "target": "timbelt",
    "target_sound": "snd/nw_timbelt_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "a",
    "item_number": "f112",
    "prime": "demenk",
    "prime_sound": "snd/nw_demenk_B.wav",
    "target": "prowent",
    "target_sound": "snd/nw_prowent_B_2.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "a",
    "item_number": "F113",
    "prime": "lomenk",
    "prime_sound": "snd/nw_lomenk_B.wav",
    "target": "summinch",
    "target_sound": "snd/nw_summinch_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "a",
    "item_number": "F114",
    "prime": "amemf",
    "prime_sound": "snd/nw_amemf_B.wav",
    "target": "flewis",
    "target_sound": "snd/nw_flewis_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "a",
    "item_number": "F115",
    "prime": "fomemf",
    "prime_sound": "snd/nw_fomemf_B.wav",
    "target": "deepelt",
    "target_sound": "snd/nw_deepelt_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "c2",
    "prime": "busy",
    "prime_sound": "snd/w_busy_B_2.wav",
    "target": "crawling",
    "target_sound": "snd/w_crawling_B_3.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "c33",
    "prime": "equal",
    "prime_sound": "snd/w_equal_B_2.wav",
    "target": "chewing",
    "target_sound": "snd/w_chewing_B_3.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "c26",
    "prime": "hiking",
    "prime_sound": "snd/w_hiking_B_2.wav",
    "target": "speaking",
    "target_sound": "snd/w_speaking_B_3.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "c27",
    "prime": "crying",
    "prime_sound": "snd/w_crying_B_2.wav",
    "target": "paying",
    "target_sound": "snd/w_paying_B.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "c9",
    "prime": "clangin",
    "prime_sound": "snd/w_clangin_B.wav",
    "target": "hugging",
    "target_sound": "snd/w_hugging_B_3.wav",
    "type": "critical",
    "c_f_type": "in",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "c30",
    "prime": "hopin",
    "prime_sound": "snd/w_hopin_B_2.wav",
    "target": "pasting",
    "target_sound": "snd/w_pasting_B_2.wav",
    "type": "critical",
    "c_f_type": "in",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "f4",
    "prime": "soccer",
    "prime_sound": "snd/w_soccer_B.wav",
    "target": "sock",
    "target_sound": "snd/w_sock_B.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "f27",
    "prime": "movement",
    "prime_sound": "snd/w_movement_B.wav",
    "target": "move",
    "target_sound": "snd/w_move_B.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "f66",
    "prime": "breathint",
    "prime_sound": "snd/nw_breathint_B.wav",
    "target": "breathe",
    "target_sound": "snd/w_breathe_B.wav",
    "type": "filler",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "f68",
    "prime": "sendink",
    "prime_sound": "snd/nw_sendink_B.wav",
    "target": "send",
    "target_sound": "snd/w_send_B.wav",
    "type": "filler",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "b",
    "item_number": "f63",
    "prime": "counting",
    "prime_sound": "snd/w_counting_B.wav",
    "target": "coump",
    "target_sound": "snd/nw_coump_B_4.wav",
    "type": "filler",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "f27",
    "prime": "moment",
    "prime_sound": "snd/w_moment_B.wav",
    "target": "mo",
    "target_sound": "snd/nw_mo_B.wav",
    "type": "filler",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "F116",
    "prime": "sarmenz",
    "prime_sound": "snd/nw_sarmenz_B.wav",
    "target": "dragolt",
    "target_sound": "snd/nw_dragolt_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "F123",
    "prime": "cademp",
    "prime_sound": "snd/nw_cademp_B.wav",
    "target": "bettulk",
    "target_sound": "snd/nw_bettulk_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "F128",
    "prime": "argemp",
    "prime_sound": "snd/nw_argemp_B.wav",
    "target": "bruschel",
    "target_sound": "snd/nw_bruschel_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "F133",
    "prime": "quib",
    "prime_sound": "snd/nw_quib_B.wav",
    "target": "vapif",
    "target_sound": "snd/nw_vapif_B_2.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "F136",
    "prime": "swip",
    "prime_sound": "snd/nw_swip_B.wav",
    "target": "bridgom",
    "target_sound": "snd/nw_bridgom_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "b",
    "item_number": "F139",
    "prime": "darp",
    "prime_sound": "snd/nw_darp_B.wav",
    "target": "gheetim",
    "target_sound": "snd/nw_gheetim_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "c14",
    "prime": "tumble",
    "prime_sound": "snd/w_tumble_B_2.wav",
    "target": "leaping",
    "target_sound": "snd/w_leaping_B_3.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "c49",
    "prime": "fancy",
    "prime_sound": "snd/w_fancy_B_2.wav",
    "target": "burning",
    "target_sound": "snd/w_burning_B.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "c32",
    "prime": "flaming",
    "prime_sound": "snd/w_flaming_B_2.wav",
    "target": "sweeping",
    "target_sound": "snd/w_sweeping_B_2.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "c39",
    "prime": "pecking",
    "prime_sound": "snd/w_pecking_B_2.wav",
    "target": "blinking",
    "target_sound": "snd/w_blinking_B.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "c51",
    "prime": "waxin",
    "prime_sound": "snd/w_waxin_B.wav",
    "target": "mixing",
    "target_sound": "snd/w_mixing_B_3.wav",
    "type": "critical",
    "c_f_type": "in",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "c44",
    "prime": "bloomin",
    "prime_sound": "snd/w_bloomin_B.wav",
    "target": "climbing",
    "target_sound": "snd/w_climbing_B_2.wav",
    "type": "critical",
    "c_f_type": "in",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "f9",
    "prime": "swimmer",
    "prime_sound": "snd/w_swimmer_B.wav",
    "target": "swim",
    "target_sound": "snd/w_swim_B.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "f32",
    "prime": "treatment",
    "prime_sound": "snd/w_treatment_B_2.wav",
    "target": "treat",
    "target_sound": "snd/w_treat_B_2.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "f34",
    "prime": "skate",
    "prime_sound": "snd/w_skate_B.wav",
    "target": "fly",
    "target_sound": "snd/w_fly_B.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "f70",
    "prime": "kissint",
    "prime_sound": "snd/nw_kissint_B.wav",
    "target": "miss",
    "target_sound": "snd/w_miss_B_2.wav",
    "type": "filler",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "c",
    "item_number": "f49",
    "prime": "comment",
    "prime_sound": "snd/w_comment_B.wav",
    "target": "com",
    "target_sound": "snd/nw_com_B.wav",
    "type": "filler",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "f57",
    "prime": "chatting",
    "prime_sound": "snd/w_chatting_B.wav",
    "target": "chaz",
    "target_sound": "snd/nw_chaz_B.wav",
    "type": "filler",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "F142",
    "prime": "sedge",
    "prime_sound": "snd/nw_sedge_B.wav",
    "target": "solix",
    "target_sound": "snd/nw_solix_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "F145",
    "prime": "tust",
    "prime_sound": "snd/nw_tust_B.wav",
    "target": "spirenk",
    "target_sound": "snd/nw_spirenk_B_2.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "F147",
    "prime": "colb",
    "prime_sound": "snd/nw_colb_B.wav",
    "target": "hundram",
    "target_sound": "snd/nw_hundram_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "F149",
    "prime": "pouk",
    "prime_sound": "snd/nw_pouk_B_2.wav",
    "target": "plighka",
    "target_sound": "snd/nw_plighka_B_2.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "F151",
    "prime": "mouk",
    "prime_sound": "snd/nw_mouk_B_2.wav",
    "target": "scuppen",
    "target_sound": "snd/nw_scuppen_B_2.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "c",
    "item_number": "F156",
    "prime": "tabe",
    "prime_sound": "snd/nw_tabe_B.wav",
    "target": "jummel",
    "target_sound": "snd/nw_jummel_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "d",
    "item_number": "c16",
    "prime": "level",
    "prime_sound": "snd/w_level_B.wav",
    "target": "stopping",
    "target_sound": "snd/w_stopping_B_3.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "c54",
    "prime": "bury",
    "prime_sound": "snd/w_bury_B.wav",
    "target": "teaching",
    "target_sound": "snd/w_teaching_B_2.wav",
    "type": "critical",
    "c_f_type": "control",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "c48",
    "prime": "plowin",
    "prime_sound": "snd/w_plowin_B_2.wav",
    "target": "growing",
    "target_sound": "snd/w_growing_B_3.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "c37",
    "prime": "messin",
    "prime_sound": "snd/w_messin_B.wav",
    "target": "spinning",
    "target_sound": "snd/w_spinning_B.wav",
    "type": "critical",
    "c_f_type": "ing",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "c56",
    "prime": "lackin",
    "prime_sound": "snd/w_lackin_B_2.wav",
    "target": "faking",
    "target_sound": "snd/w_faking_B.wav",
    "type": "critical",
    "c_f_type": "in",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "c13",
    "prime": "carvin",
    "prime_sound": "snd/w_carvin_B_2.wav",
    "target": "dreaming",
    "target_sound": "snd/w_dreaming_B.wav",
    "type": "critical",
    "c_f_type": "in",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "f36",
    "prime": "milk",
    "prime_sound": "snd/w_milk_B.wav",
    "target": "push",
    "target_sound": "snd/w_push_B_2.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "f14",
    "prime": "winner",
    "prime_sound": "snd/w_winner_B.wav",
    "target": "win",
    "target_sound": "snd/w_win_B.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "f22",
    "prime": "basement",
    "prime_sound": "snd/w_basement_B.wav",
    "target": "base",
    "target_sound": "snd/w_base_B.wav",
    "type": "filler",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "f77",
    "prime": "bankert",
    "prime_sound": "snd/nw_bankert_B.wav",
    "target": "thank",
    "target_sound": "snd/w_thank_B.wav",
    "type": "filler",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "f88",
    "prime": "foolint",
    "prime_sound": "snd/nw_foolint_B.wav",
    "target": "pool",
    "target_sound": "snd/w_pool_B.wav",
    "type": "filler",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "d",
    "item_number": "f48",
    "prime": "brother",
    "prime_sound": "snd/w_brother_B.wav",
    "target": "broth",
    "target_sound": "snd/nw_broth_B.wav",
    "type": "filler",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "d",
    "item_number": "F164",
    "prime": "tral",
    "prime_sound": "snd/nw_tral_B.wav",
    "target": "smertha",
    "target_sound": "snd/nw_smertha_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "d",
    "item_number": "F168",
    "prime": "niyn",
    "prime_sound": "snd/nw_niyn_B.wav",
    "target": "luhd",
    "target_sound": "snd/nw_luhd_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "d",
    "item_number": "F169",
    "prime": "gowg",
    "prime_sound": "snd/nw_gowg_B_4.wav",
    "target": "nihldz",
    "target_sound": "snd/nw_nihldz_B_2.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "d",
    "item_number": "F173",
    "prime": "skihjh",
    "prime_sound": "snd/nw_skihjh_B.wav",
    "target": "tehjh",
    "target_sound": "snd/nw_tehjh_B_3.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "d",
    "item_number": "F179",
    "prime": "plehl",
    "prime_sound": "snd/nw_plehl_B_2.wav",
    "target": "kaek",
    "target_sound": "snd/nw_kaek_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "d",
    "item_number": "F195",
    "prime": "slihg",
    "prime_sound": "snd/nw_slihg_B_2.wav",
    "target": "trahm",
    "target_sound": "snd/nw_trahm_B.wav",
    "type": "filler",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "practice",
    "item_number": "p1",
    "prime": "bully",
    "prime_sound": "snd/w_bully_B.wav",
    "target": "itching",
    "target_sound": "snd/w_itching_B_2.wav",
    "type": "practice",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "practice",
    "item_number": "p2",
    "prime": "cooking",
    "prime_sound": "snd/w_cooking_B_3.wav",
    "target": "ruining",
    "target_sound": "snd/w_ruining_B.wav",
    "type": "practice",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "practice",
    "item_number": "p3",
    "prime": "brushing",
    "prime_sound": "snd/w_brushing_B_3.wav",
    "target": "riddle",
    "target_sound": "snd/w_riddle_B.wav",
    "type": "practice",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "practice",
    "item_number": "p4",
    "prime": "knocking",
    "prime_sound": "snd/w_knocking_B_3.wav",
    "target": "bragging",
    "target_sound": "snd/w_bragging_B_2.wav",
    "type": "practice",
    "c_f_type": "rr",
    "prime_type": "r",
    "target_type": "r",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "practice",
    "item_number": "p5",
    "prime": "touchint",
    "prime_sound": "snd/nw_touchint_B.wav",
    "target": "spraying",
    "target_sound": "snd/w_spraying_B.wav",
    "type": "practice",
    "c_f_type": "nr",
    "prime_type": "n",
    "target_type": "r",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-real.png"
  },
  {
    "block": "practice",
    "item_number": "p6",
    "prime": "clicking",
    "prime_sound": "snd/w_clicking_B_3.wav",
    "target": "buzzerp",
    "target_sound": "snd/nw_buzzerp_B.wav",
    "type": "practice",
    "c_f_type": "rn",
    "prime_type": "r",
    "target_type": "n",
    "prime_correct": "img/fish-real.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "practice",
    "item_number": "p7",
    "prime": "waske",
    "prime_sound": "snd/nw_waske_B.wav",
    "target": "thwoxit",
    "target_sound": "snd/nw_thwoxit_B.wav",
    "type": "practice",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "practice",
    "item_number": "p8",
    "prime": "vowp",
    "prime_sound": "snd/nw_vowp_B_3.wav",
    "target": "snowast",
    "target_sound": "snd/nw_snowast_B.wav",
    "type": "practice",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "practice",
    "item_number": "p9",
    "prime": "broon",
    "prime_sound": "snd/nw_broon_B.wav",
    "target": "ploufip",
    "target_sound": "snd/nw_ploufip_B.wav",
    "type": "practice",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  },
  {
    "block": "practice",
    "item_number": "p10",
    "prime": "resk",
    "prime_sound": "snd/nw_resk_B.wav",
    "target": "crayint",
    "target_sound": "snd/nw_crayint_B.wav",
    "type": "practice",
    "c_f_type": "nn",
    "prime_type": "n",
    "target_type": "n",
    "prime_correct": "img/fish-silly.png",
    "target_correct": "img/fish-silly.png"
  }
]